package com.lab.jan_21;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Random;

public class HospitalService 
{
	private int hospitalCode = 100;
	List<Hospital> hospitalList = new ArrayList<Hospital>();

	public int addHospital( String hospitalName, String contactPerson, List<String> listOfTreatments,
			String contactNumber, String location)
	{
		
		
		hospitalCode++;
		
		hospitalList.add(new Hospital(hospitalCode, hospitalName, listOfTreatments, contactPerson, contactNumber, location));
		return hospitalCode;
	}
	
	public Map<Integer, String> getHospitals()
	{
		Map<Integer, String> hpMap = new HashMap<Integer, String>();
		for(Hospital hp : hospitalList )
		{
			hpMap.put(hp.getHospitalCode(), hp.getHospitalName());
		}
		return hpMap;
	}
	
	public Hospital getHospitalDetails(int hospitalCode)
	{
		for(Hospital hp : hospitalList)
		{
			if(hp.getHospitalCode()==hospitalCode)
				return hp;
		}
		return null;
	}
}
/*
A class HospitalService is given to you. Implement the following features in the class.
Methods : public 
addHospital(): This method should receive hospital details 
 as arguments and add to ArrayList of type Hospital and return the generated hospital 
code.
Note : Hospital Code is not given as argument but it should be 
 autogenerated while creating object. It should start from 100.
 getHospitals() : This method should return existing hospitals 
names and its codes in the form of Map variable that contains Hospital 
Code as key (Integer) and Hospital name as Value (String).
 getHospitalDetails() : This method should receive hospital code 
as argument and return the matching object of hospital after searching in 
the ArrayList. Return null if object not found.
*/